name: Run Tests

on:
  push:
    branches:
      - main
      - feature/ticketsystem
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install PHP dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend assets with Vite
        run: npm run build

      - name: Run tests with Pest
        run: ./vendor/bin/pest --colors
